### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by Ryko24** [ZIB-IOL/BellPolytopes.jl#6]
Cannot create pull request

**Comment by matbesancon** [comment]
hi @Ryko24, I'm not sure to understand what you mean here? Did you try to open a Pull Request on the package and it didn't work?

**Comment by Ryko24** [comment]
Thank you @matbesancon.... my query got answered... I looked for it online.. and found the remedy... actually I am a beginner and was facing some isssue...
